image: bradrydzewski/php:5.5

services:
  - mysql
script:
  - sudo apt-get update && sudo apt-get install php5
  - sudo composer self-update
  - composer install --no-interaction --prefer-source 
  - cp .env.example .env
  - php artisan key:generate
  - mysql -e 'create database learn;'
  - php artisan --env=testing migrate
  - php artisan --env=testing db:seed

